# Generated by Django 5.0.7 on 2024-07-16 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyexpert',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
