# Generated by Django 5.0.7 on 2024-07-17 01:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': '이 유저명은 이미 사용 중입니다.'}, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='유저명은 알파벳, 숫자, 밑줄 및 점만 포함할 수 있습니다.', regex='^[\\w.]+$')]),
        ),
    ]
