# Generated by Django 5.0.7 on 2024-07-23 00:07

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=22, max_length=128, prefix='', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='제목')),
                ('label', models.CharField(choices=[('업무', '업무'), ('개인', '개인'), ('가족', '가족'), ('휴일', '휴일'), ('기타', '기타')], max_length=20, verbose_name='라벨')),
                ('start_date', models.DateTimeField(verbose_name='시작일')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='종료일')),
                ('all_day', models.BooleanField(default=False, verbose_name='종일')),
                ('event_url', models.URLField(blank=True, null=True, verbose_name='이벤트 URL')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='위치')),
                ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
            ],
        ),
    ]
