# Generated by Django 5.0.6 on 2024-07-23 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PortfolioEditor',
        ),
    ]
