# Generated by Django 5.0.6 on 2024-07-17 07:46

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioEditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('htmlcontent', tinymce.models.HTMLField()),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editors', to='portfolios.portfolio')),
            ],
        ),
    ]
