# Generated by Django 5.0.6 on 2024-07-18 00:38

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_portfolioeditor'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='htmlcontent',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
